"""3.10.1

Revision ID: ad3313fe4368
Revises: be8c801ba4c9
Create Date: 2025-08-20 09:34:54.955271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3313fe4368'
down_revision = 'be8c801ba4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bpmin_it',
    sa.Column('it_manager', sa.String(length=100), nullable=True, comment='IT經理'),
    sa.Column('dept', sa.String(length=50), nullable=True, comment='部門'),
    sa.Column('apply_date', sa.String(length=20), nullable=True, comment='申請日期'),
    sa.Column('extension', sa.String(length=20), nullable=True, comment='分機號碼'),
    sa.Column('fillman', sa.String(length=100), nullable=True, comment='填表人'),
    sa.Column('main_apply_item', sa.String(length=200), nullable=True, comment='申請項目'),
    sa.Column('sub_apply_item', sa.String(length=200), nullable=True, comment='子申請項目'),
    sa.Column('request_desc', sa.String(length=500), nullable=True, comment='需求描述'),
    sa.Column('it_undertaker', sa.String(length=100), nullable=True, comment='IT承辦人'),
    sa.Column('treatment', sa.String(length=500), nullable=True, comment='處理方式'),
    sa.Column('serial_number', sa.String(length=50), nullable=True, comment='序號'),
    sa.Column('datediff', sa.Float(), nullable=True, comment='處理天數'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者工號'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.PrimaryKeyConstraint('id'),
    comment='IT service request form'
    )
    op.create_table('Bpmin_it_detail',
    sa.Column('work_desc', sa.String(length=500), nullable=True, comment='工作描述'),
    sa.Column('rsn', sa.String(length=50), nullable=True, comment='參照序號'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='狀態'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='IT service request details'
    )
    op.create_table('vadmin_auth_dept',
    sa.Column('name', sa.String(length=50), nullable=False, comment='部門名稱'),
    sa.Column('dept_key', sa.String(length=50), nullable=False, comment='部門標示'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('order', sa.Integer(), nullable=True, comment='顯示排序'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('owner', sa.String(length=255), nullable=True, comment='負責人'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='聯絡電話'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='郵箱'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部門'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['parent_id'], ['vadmin_auth_dept.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='部門表'
    )
    op.create_index(op.f('ix_vadmin_auth_dept_dept_key'), 'vadmin_auth_dept', ['dept_key'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_dept_name'), 'vadmin_auth_dept', ['name'], unique=False)
    op.create_table('vadmin_auth_menu',
    sa.Column('title', sa.String(length=50), nullable=False, comment='名稱'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜單圖標'),
    sa.Column('redirect', sa.String(length=100), nullable=True, comment='重定向地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件地址'),
    sa.Column('path', sa.String(length=50), nullable=True, comment='前端路由地址'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隱藏'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('menu_type', sa.String(length=8), nullable=False, comment='菜單類型'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜單'),
    sa.Column('perms', sa.String(length=50), nullable=True, comment='權限標識'),
    sa.Column('noCache', sa.Boolean(), nullable=False, comment='如果设置為true，则不會被 <keep-alive> 缓存(默认 false)'),
    sa.Column('breadcrumb', sa.Boolean(), nullable=False, comment='如果设置為false，则不會在breadcrumb面包屑中显示(默认 true)'),
    sa.Column('affix', sa.Boolean(), nullable=False, comment='如果设置為true，则會一直固定在tag項中(默认 false)'),
    sa.Column('noTagsView', sa.Boolean(), nullable=False, comment='如果设置為true，则不會出现在tag中(默认 false)'),
    sa.Column('canTo', sa.Boolean(), nullable=False, comment='设置為true即使hidden為true，也依然可以進行路由跳转(默认 false)'),
    sa.Column('alwaysShow', sa.Boolean(), nullable=False, comment='當你一个路由下面的 children 声明的路由大于1个時，自動會变成嵌套的模式，\n    只有一个時，會将那个子路由當做根路由显示在侧边栏，若你想不管路由下面的 children 声明的个數都显示你的根路由，\n    你可以设置 alwaysShow: true，这樣它就會忽略之前定义的规则，一直显示根路由(默认 true)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['parent_id'], ['vadmin_auth_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='選單表'
    )
    op.create_index(op.f('ix_vadmin_auth_menu_perms'), 'vadmin_auth_menu', ['perms'], unique=False)
    op.create_table('vadmin_auth_role',
    sa.Column('name', sa.String(length=50), nullable=False, comment='名稱'),
    sa.Column('role_key', sa.String(length=50), nullable=False, comment='權限字符'),
    sa.Column('data_range', sa.Integer(), nullable=False, comment='數據權限范围'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否為超级角色'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index(op.f('ix_vadmin_auth_role_name'), 'vadmin_auth_role', ['name'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_role_role_key'), 'vadmin_auth_role', ['role_key'], unique=False)
    op.create_table('vadmin_auth_user',
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像'),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='帳號'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='郵箱地址'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵稱'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密碼'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('is_reset_password', sa.Boolean(), nullable=False, comment='是否已經重置密碼，没有重置的，登陆系统后必须重置密碼'),
    sa.Column('last_ip', sa.String(length=50), nullable=True, comment='最后一次登錄IP'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最近一次登錄時間'),
    sa.Column('is_staff', sa.Boolean(), nullable=False, comment='是否為工作人员'),
    sa.Column('wx_server_openid', sa.String(length=255), nullable=True, comment='服務端微信平台openid'),
    sa.Column('is_wx_server_openid', sa.Boolean(), nullable=False, comment='是否已有服務端微信平台openid'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_vadmin_auth_user_name'), 'vadmin_auth_user', ['name'], unique=False)
    op.create_index(op.f('ix_vadmin_auth_user_telephone'), 'vadmin_auth_user', ['telephone'], unique=False)
    op.create_table('vadmin_record_login',
    sa.Column('telephone', sa.String(length=255), nullable=False, comment='帳號'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='是否登錄成功'),
    sa.Column('platform', sa.String(length=8), nullable=False, comment='登陆平台'),
    sa.Column('login_method', sa.String(length=8), nullable=False, comment='認證方式'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='登陆地点'),
    sa.Column('country', sa.String(length=255), nullable=True, comment='国家'),
    sa.Column('province', sa.String(length=255), nullable=True, comment='县'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='城市'),
    sa.Column('county', sa.String(length=255), nullable=True, comment='区/县'),
    sa.Column('operator', sa.String(length=255), nullable=True, comment='运营商'),
    sa.Column('postal_code', sa.String(length=255), nullable=True, comment='郵政编碼'),
    sa.Column('area_code', sa.String(length=255), nullable=True, comment='地区区号'),
    sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
    sa.Column('system', sa.String(length=50), nullable=True, comment='操作系统'),
    sa.Column('response', sa.Text(), nullable=True, comment='响应信息'),
    sa.Column('request', sa.Text(), nullable=True, comment='請求信息'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='登錄记錄表'
    )
    op.create_index(op.f('ix_vadmin_record_login_telephone'), 'vadmin_record_login', ['telephone'], unique=False)
    op.create_table('vadmin_system_dict_type',
    sa.Column('dict_name', sa.String(length=50), nullable=False, comment='字典名稱'),
    sa.Column('dict_type', sa.String(length=50), nullable=False, comment='字典類型'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='字典状態，是否禁用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典類型表'
    )
    op.create_index(op.f('ix_vadmin_system_dict_type_dict_name'), 'vadmin_system_dict_type', ['dict_name'], unique=False)
    op.create_index(op.f('ix_vadmin_system_dict_type_dict_type'), 'vadmin_system_dict_type', ['dict_type'], unique=False)
    op.create_table('vadmin_system_settings_tab',
    sa.Column('title', sa.String(length=255), nullable=False, comment='標题'),
    sa.Column('classify', sa.String(length=255), nullable=False, comment='分类键'),
    sa.Column('tab_label', sa.String(length=255), nullable=False, comment='tab標题'),
    sa.Column('tab_name', sa.String(length=255), nullable=False, comment='tab標识符'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隐藏'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置分类表'
    )
    op.create_index(op.f('ix_vadmin_system_settings_tab_classify'), 'vadmin_system_settings_tab', ['classify'], unique=False)
    op.create_index(op.f('ix_vadmin_system_settings_tab_tab_name'), 'vadmin_system_settings_tab', ['tab_name'], unique=True)
    op.create_table('vadmin_auth_role_depts',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['vadmin_auth_dept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], ondelete='CASCADE')
    )
    op.create_table('vadmin_auth_role_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['vadmin_auth_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], ondelete='CASCADE')
    )
    op.create_table('vadmin_auth_user_depts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['vadmin_auth_dept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], ondelete='CASCADE')
    )
    op.create_table('vadmin_auth_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], ondelete='CASCADE')
    )
    op.create_table('vadmin_help_issue_category',
    sa.Column('name', sa.String(length=50), nullable=False, comment='类别名稱'),
    sa.Column('platform', sa.String(length=8), nullable=False, comment='展示平台'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='創建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见問题类别表'
    )
    op.create_index(op.f('ix_vadmin_help_issue_category_name'), 'vadmin_help_issue_category', ['name'], unique=False)
    op.create_index(op.f('ix_vadmin_help_issue_category_platform'), 'vadmin_help_issue_category', ['platform'], unique=False)
    op.create_table('vadmin_record_sms_send',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='發送状態'),
    sa.Column('content', sa.String(length=255), nullable=False, comment='發送内容'),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='目標帳號'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='失敗描述'),
    sa.Column('scene', sa.String(length=50), nullable=True, comment='發送场景'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信發送记錄表'
    )
    op.create_table('vadmin_resource_images',
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原圖片名稱'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='圖片链接'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='創建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='圖片素材表'
    )
    op.create_table('vadmin_system_dict_details',
    sa.Column('label', sa.String(length=50), nullable=False, comment='字典標籤'),
    sa.Column('value', sa.String(length=50), nullable=False, comment='字典键值'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='字典状態，是否禁用'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认'),
    sa.Column('order', sa.Integer(), nullable=False, comment='字典排序'),
    sa.Column('dict_type_id', sa.Integer(), nullable=False, comment='關聯字典類型'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['vadmin_system_dict_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典詳情表'
    )
    op.create_index(op.f('ix_vadmin_system_dict_details_label'), 'vadmin_system_dict_details', ['label'], unique=False)
    op.create_index(op.f('ix_vadmin_system_dict_details_value'), 'vadmin_system_dict_details', ['value'], unique=False)
    op.create_table('vadmin_system_settings',
    sa.Column('config_label', sa.String(length=255), nullable=False, comment='配置表標籤'),
    sa.Column('config_key', sa.String(length=255), nullable=False, comment='配置表键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置表内容'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('tab_id', sa.Integer(), nullable=False, comment='關聯tab標籤'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('create_user', sa.String(length=30), nullable=True, comment='建立者'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['tab_id'], ['vadmin_system_settings_tab.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表'
    )
    op.create_index(op.f('ix_vadmin_system_settings_config_key'), 'vadmin_system_settings', ['config_key'], unique=True)
    op.create_table('vadmin_help_issue',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='类别'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='標题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('view_number', sa.Integer(), nullable=False, comment='查看次數'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='創建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主鍵ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='創建時間'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='刪除時間'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否軟刪除'),
    sa.Column('update_user', sa.String(length=30), nullable=True, comment='更新者'),
    sa.Column('delete_user', sa.String(length=30), nullable=True, comment='刪除者'),
    sa.ForeignKeyConstraint(['category_id'], ['vadmin_help_issue_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见問题记錄表'
    )
    op.create_index(op.f('ix_vadmin_help_issue_title'), 'vadmin_help_issue', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vadmin_help_issue_title'), table_name='vadmin_help_issue')
    op.drop_table('vadmin_help_issue')
    op.drop_index(op.f('ix_vadmin_system_settings_config_key'), table_name='vadmin_system_settings')
    op.drop_table('vadmin_system_settings')
    op.drop_index(op.f('ix_vadmin_system_dict_details_value'), table_name='vadmin_system_dict_details')
    op.drop_index(op.f('ix_vadmin_system_dict_details_label'), table_name='vadmin_system_dict_details')
    op.drop_table('vadmin_system_dict_details')
    op.drop_table('vadmin_resource_images')
    op.drop_table('vadmin_record_sms_send')
    op.drop_index(op.f('ix_vadmin_help_issue_category_platform'), table_name='vadmin_help_issue_category')
    op.drop_index(op.f('ix_vadmin_help_issue_category_name'), table_name='vadmin_help_issue_category')
    op.drop_table('vadmin_help_issue_category')
    op.drop_table('vadmin_auth_user_roles')
    op.drop_table('vadmin_auth_user_depts')
    op.drop_table('vadmin_auth_role_menus')
    op.drop_table('vadmin_auth_role_depts')
    op.drop_index(op.f('ix_vadmin_system_settings_tab_tab_name'), table_name='vadmin_system_settings_tab')
    op.drop_index(op.f('ix_vadmin_system_settings_tab_classify'), table_name='vadmin_system_settings_tab')
    op.drop_table('vadmin_system_settings_tab')
    op.drop_index(op.f('ix_vadmin_system_dict_type_dict_type'), table_name='vadmin_system_dict_type')
    op.drop_index(op.f('ix_vadmin_system_dict_type_dict_name'), table_name='vadmin_system_dict_type')
    op.drop_table('vadmin_system_dict_type')
    op.drop_index(op.f('ix_vadmin_record_login_telephone'), table_name='vadmin_record_login')
    op.drop_table('vadmin_record_login')
    op.drop_index(op.f('ix_vadmin_auth_user_telephone'), table_name='vadmin_auth_user')
    op.drop_index(op.f('ix_vadmin_auth_user_name'), table_name='vadmin_auth_user')
    op.drop_table('vadmin_auth_user')
    op.drop_index(op.f('ix_vadmin_auth_role_role_key'), table_name='vadmin_auth_role')
    op.drop_index(op.f('ix_vadmin_auth_role_name'), table_name='vadmin_auth_role')
    op.drop_table('vadmin_auth_role')
    op.drop_index(op.f('ix_vadmin_auth_menu_perms'), table_name='vadmin_auth_menu')
    op.drop_table('vadmin_auth_menu')
    op.drop_index(op.f('ix_vadmin_auth_dept_name'), table_name='vadmin_auth_dept')
    op.drop_index(op.f('ix_vadmin_auth_dept_dept_key'), table_name='vadmin_auth_dept')
    op.drop_table('vadmin_auth_dept')
    op.drop_table('Bpmin_it_detail')
    op.drop_table('Bpmin_it')
    # ### end Alembic commands ###
